---
title: portfolio-samples
description: a selection of technical writing examples
url: https://firoyj.github.io/portfolio-samples/
remote_theme: pages-themes/modernist@v0.2.0
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  coderay:
    line_numbers: false
    tab_width: 2
    css: style
---
